name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.10-dind
        privileged: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push
        working-directory: .  # Use the root directory where docker-compose.yml is located

      #PAT added to personal account setting to login. Needed for this step
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

     # - name: Push Docker Image
     #   run: docker push ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest
